### PR TITLE
Added groups info call

### PR DESCRIPTION
**Pull request by qbanguy**

### CODE REVIEW

**Comment by alanshaw** [comment]
Would be awesome if you merged and released this

**Comment by RexMorgan** [comment]
Thanks, very long delay on this, sorry. I'll try to test all there pull requests and make a new release shortly.

**Comment by RexMorgan** [comment]
@qbanguy @alanshaw 

This is in 0.3.0 that was released to npmjs.com a couple of hours ago.

Thanks again!

**Comment by asanchezdelc** [comment]
@RexMorgan Thanks!

**Comment by qbanguy** [comment]
@RexMorgan Thanks!

**Pull request merged**
